<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('HelloSign PHP Samples')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            // ->setCharset('utf-8')
            ->setName('og:image', $this->basePath() . '/img/image.png')
            ->setName('og:type', 'website')
            ->setName('og:site_name', 'HelloSign')
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->headLink(array('rel' => 'apple-touch-icon', 'href' => $this->basePath() . '/img/apple-touch-icon-precomposed.png'))
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile('//s3.amazonaws.com/cdn.hellofax.com/js/embedded.js')
            ->prependFile($this->basePath() . '/js/fake-file-input.js')
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php echo $this->url('home') ?>"><img src="<?php echo $this->basePath('img/logo.png') ?>" alt="HelloSign"/></a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li class="active"><a href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Home') ?></a></li>
                    </ul>
                </div><!--/.nav-collapse -->
            </div>
        </nav>
        <div class="container">
            <?php echo $this->content; ?>
        </div> <!-- /container -->
        <?php
            $script = <<<SCRIPT
function addElement(i) {
    if (!i) {
        i = 0;
    }
    var currentCount = $('form > fieldset:nth('+i+') > fieldset').length;
    var template = $('form > fieldset > span:nth('+i+')').data('template');
    template = template
        .replace(/__index__/g, currentCount)
        // hard code for BT3
        .replace(/<label class="col-sm-2">/g, '<label class="col-sm-2 control-label">')
        .replace(/ col-sm-10/g, '')
        .replace(/<\/label>/g, '</label><div class="col-sm-10">')
        .replace(/<\/div>/g, '</div></div>');

    $('form > fieldset:nth('+i+')').append(template);

    return false;
}
SCRIPT;
            echo $this->inlineScript()->appendScript($script) ?>
    </body>
</html>
